#:schema ./schema/mise.json

min_version = "2024.1.1"
[env]
_.file = [".env"]
_.path = ["./target/debug", "./node_modules/.bin"]
FOO = "bar"
FOO_NUM = 1
THIS_PROJECT = "{{config_root}}-{{cwd}}"
CERTIFICATES_DIR = "{{config_root}}/private/certificates/live/"


[tools]
bun = "latest"
terraform = "latest"
jq = "latest"
shellcheck = "latest"
python = "3.12"
node = "lts"
go = "1.23"
rust = "1.81"
ruby = "3.3"


[plugins]
nnnn = 'https://github.com/mise-plugins/rtx-nodejs#main'

[alias.tiny]
abc = '1'
