#:schema ./schema/mise.json

min_version = "2024.1.1"
[env]
_.file = [".env"]
_.path = ["./target/debug"]
FOO = "bar"
FOO_NUM = 1
THIS_PROJECT = "{{config_root}}-{{cwd}}"
GCP_SQL_INSTANCE = "dev-nino:us-central1:postgre"
LOCAL_SQL_PORT = "15432"
EXPECTED_PYTHON_VERSION = "3.10.8"
EXPECTED_NVCC_VERSION = "11.2"
EXPECTED_CONDA_VERSION = "23.9.0"
EXPECTED_TORCH_VERSION = "1.8.1"

[tools]
python = { version = '3.11', virtualenv = '.venv' }
bun = "latest"


[plugins]
nnnn = 'https://github.com/mise-plugins/rtx-nodejs#main'

[alias.tiny]
abc = '1'
