#:schema ./schema/mise.json

min_version = "2024.1.1"
[env]
_.file = [".env"]
_.path = ["./target/debug"]
FOO = "bar"
FOO_NUM = 1
THIS_PROJECT = "{{config_root}}-{{cwd}}"


[tools]
python = "latest"
bun = "latest"
rust = "latest"
go = "latest"
node = "latest"
terraform = "latest"
direnv = "latest"
jq = "latest"
shellcheck = "latest"


[plugins]
nnnn = 'https://github.com/mise-plugins/rtx-nodejs#main'

[alias.tiny]
abc = '1'
