min_version = "2024.1.1"

[env]
_.file = [".env"] # encrypted by dotenvx
# below as plain dotenv
THIS_PROJECT = "{{config_root}}-{{cwd}}"
CERTIFICATES_DIR = "{{config_root}}/private/certificates/live/"
WORLD = "hello"


[tools]
bun = "latest"
terraform = "latest"
jq = "latest"
shellcheck = "latest"
python = "3.12"
node = "lts"
go = "1.23"
rust = "1.82.0"
ruby = "3.3"


[plugins]
nnnn = 'https://github.com/mise-plugins/rtx-nodejs#main'
