min_version = "2025.2.7"

[env]
# encrypted by dotenvx `dotenvx set HELLO value` or `dotenvx set NODE_ENV development --plain`
_.file = [".env"]
# below by mise env `mise set NODE_ENV=development`
THIS_PROJECT = "{{config_root}}-{{cwd}}"
CERTIFICATES_DIR = "{{config_root}}/private/certificates/live/"


[tools]
shellcheck = "latest"
python = "3.13"
node = "lts"
go = "1.24"
ruby = "latest"


[tasks]
format = "echo 'TODO'"
test = "echo 'TODO'"

[tasks.code]
run = "code vs.code-workspace"
alias = "c"

[tasks."stack:tf:ls"]
run = "tofu workspace list"
dir = "stacks/hironow"

[tasks."stack:tm:ls"]
run = "terramate list"
