min_version = "2024.1.1"

[env]
# encrypted by dotenvx `dotenvx set HELLO value` or `dotenvx set NODE_ENV development --plain`
_.file = [".env"]
# below as plain dotenv `mise set NODE_ENV=development`
THIS_PROJECT = "{{config_root}}-{{cwd}}"
CERTIFICATES_DIR = "{{config_root}}/private/certificates/live/"


[tools]
bun = "1.1.42"
deno = "2.1.4"
erlang = "27.2"
go = "1.23.4"
node = "22.12.0"
python = "3.13.0"
shellcheck = "0.10.0"
terraform = "1.10.3"


[tasks]
format = "echo 'TODO'"
test = "echo 'TODO'"

[tasks.code]
run = "code dotfiles.code-workspace"
alias = "c"
