[project]
name = "dotfiles"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "google-generativeai>=0.7.2",
    "datasets>=2.21.0",
    "openai>=1.42.0",
    "set-env-colab-kaggle-dotenv>=0.1.2",
    "anthropic>=0.34.1",
    "weave>=0.50.14",
    "filetype>=1.2.0",
    "pydantic>=2.8.2",
    "pypdf>=4.3.1",
    "requests>=2.32.3",
    "fastapi>=0.112.1",
    "typer>=0.12.4",
    "cloudevents>=1.11.0",
    "pandas>=2.2.2",
    "pillow>=10.4.0",
    "tiktoken>=0.7.0",
    "firebase-admin>=6.5.0",
    "google-cloud-firestore>=2.17.2",
    "google-cloud-storage>=2.18.2",
    "pydantic-settings>=2.4.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
dev-dependencies = [
    "ruff>=0.6.2",
    "pytest>=8.3.2",
    "pytest-playwright>=0.5.1",
    "pytest-mock>=3.14.0",
    "mock-firestore>=0.11.0",
    "wandb>=0.17.7",
    "ipykernel>=6.29.5",
    "ipywidgets>=8.1.5",
]
