#!/usr/bin/env bash
# Render docs/portless-urls.md from portless alias pairs on stdin.
#
# Pure formatter: reads "name port" lines (as emitted by `just _portless-pairs`)
# and writes the Markdown doc to stdout. Kept out of the justfile so the
# Markdown is not mangled by recipe indentation. Idempotent — same input always
# yields byte-identical output, so `just portless-doc-check` can diff it.
#
# Usage:
#   just _portless-pairs | scripts/generate-portless-doc.sh
#
# shellcheck disable=SC2016  # %s in the printf formats are placeholders, not shell expansions
set -euo pipefail

pairs="$(cat)"

# name -> ENV VAR stem: uppercase, '-' -> '_'. e.g. a2a-inspector -> A2A_INSPECTOR
env_stem() { printf '%s' "$1" | tr 'a-z-' 'A-Z_'; }

cat <<'HEADER'
# Portless URLs

<!-- GENERATED by `just portless-doc` from config/portless-aliases.yaml — do not edit by hand. -->

Local-dev HTTP UIs are reachable as stable `https://<name>.localhost` URLs through the portless
HTTPS proxy. Bring the proxy up with `just portless-up`, then start the backing stack
(`just tel-up` / `just emu-start` / `just emu-api`). Raw TCP wire protocols are not
portless-routable and are intentionally omitted (see `config/portless-aliases.yaml`).

| Service | Local port | Portless URL | Suggested env var |
| --- | --- | --- | --- |
HEADER

while read -r name port; do
  [ -z "$name" ] && continue
  printf '| %s | `127.0.0.1:%s` | `https://%s.localhost` | `%s_URL` |\n' \
    "$name" "$port" "$name" "$(env_stem "$name")"
done <<<"$pairs"

cat <<'MID'

## .env snippet

```dotenv
MID

while read -r name port; do
  [ -z "$name" ] && continue
  printf '%s_URL=https://%s.localhost\n' "$(env_stem "$name")" "$name"
done <<<"$pairs"

printf '```\n'
