#!/usr/bin/env bash

# ==============================================================================
# Development environment hardening (machine-local; ADR 0028)
# ------------------------------------------------------------------------------
# Writes the supply-chain guards that must NOT live in the committed repo:
#   - npm  ~/.npmrc               min-release-age=7 (7-day quarantine)
#   - uv   ~/.config/uv/uv.toml   flatt mirror (default index) + exclude-newer=7d
#   - go   GOPROXY                default checksum-verified proxy (if go present)
#
# Portable across GNU (Linux/WSL) and BSD (macOS): it uses NO `sed -i` at all,
# and is idempotent (safe to re-run — no duplicated lines).
#
# NOT written here: the pip index-url / pip-alias hardening block. That already
# lives in the tracked `.zshrc` and ships via `just deploy`; writing it here
# would dirty the symlinked repo file and duplicate on every re-run.
# ==============================================================================

set -eu

echo "--- 🛡️  Hardening environment (flatt mirror + 7-day quarantine) ---"

# 1. npm — idempotent min-release-age upsert (portable; no sed -i).
_npmrc="$HOME/.npmrc"
echo "[1/3] npm: ${_npmrc} (min-release-age=7)"
_tmp="$(mktemp)"
if [ -f "$_npmrc" ]; then
  # Drop any prior min-release-age line; `|| true` because grep -v exits 1
  # when every line is filtered out (e.g. a one-line file).
  grep -v '^min-release-age' "$_npmrc" >"$_tmp" || true
fi
printf 'min-release-age=7\n' >>"$_tmp"
mv "$_tmp" "$_npmrc"

# 2. uv — flatt default index + 7-day quarantine (overwrite = idempotent).
_uv_dir="$HOME/.config/uv"
echo "[2/3] uv: ${_uv_dir}/uv.toml (flatt default index + exclude-newer)"
mkdir -p "$_uv_dir"
cat >"${_uv_dir}/uv.toml" <<'EOF'
# Generated by scripts/harden_env.sh (machine-local; ADR 0028).
exclude-newer = "7 days"

[[index]]
name = "flatt"
url = "https://pypi.flatt.tech/simple/"
default = true
EOF

# 3. go — default checksum-verified proxy (only if go is installed).
echo "[3/3] go: GOPROXY (default) if go is installed"
if command -v go >/dev/null 2>&1; then
  go env -w GOPROXY="https://proxy.golang.org,direct"
  echo "  - GOPROXY set to the default checksummed proxy"
else
  echo "  - go not on PATH; skipping"
fi

echo "--- ✅ Hardening applied (machine-local; not tracked in the repo) ---"
