#!/bin/bash

# ==============================================================================
# Development Environment Hardening Script (with Flatt Security Proxy)
# Targets: npm, pnpm, bun, uv, python (pip), rust, go, viteplus
# ==============================================================================

set -u

echo "--- 🛡️  Starting environment hardening (7-day rule & Proxy Guard) ---"

# 1. Node.js Ecosystem (npm, pnpm, viteplus)
NPMRC="$HOME/.npmrc"
echo "[1/5] Configuring Node.js ecosystem..."
[ -f "$NPMRC" ] && sed -i '' '/min-release-age/d' "$NPMRC"
echo "min-release-age=7" >> "$NPMRC"
echo "  - Added 'min-release-age=7' to $NPMRC"


# 2. Python Ecosystem (uv & pip with Flatt Proxy)
echo "[2/5] Configuring Python ecosystem with Flatt Proxy..."

# uv の設定: index-url を Flatt Proxy に向け、かつ 7-day rule を適用
UV_CONFIG_DIR="$HOME/.config/uv"
UV_TOML="$UV_CONFIG_DIR/uv.toml"
mkdir -p "$UV_CONFIG_DIR"
cat << EOF > "$UV_TOML"
# Generated by hardening script
exclude-newer = "7 days"

[[index]]
name = "flatt"
url = "https://pypi.flatt.tech/simple/"
default = true
EOF
echo "  - Configured $UV_TOML with 7-day rule and Flatt Proxy"


# 3. Shell Integration (PIP_INDEX_URL & Aliases)
SHELL_RC="$HOME/.zshrc"
[ ! -f "$SHELL_RC" ] && SHELL_RC="$HOME/.bashrc"

echo "[3/5] Updating shell configuration ($SHELL_RC)..."

# 既存の関連設定を削除（クリーンアップ）
sed -i '' '/# Security Hardening/,/# End Security/d' "$SHELL_RC"

cat << 'EOF' >> "$SHELL_RC"

# --- Security Hardening (Added by script) ---
# Enforce Flatt Security's PyPI Proxy for pip
export PIP_INDEX_URL="https://pypi.flatt.tech/simple/"

# Use uv for python packages where possible
alias pip='uv pip'
# --- End Security ---
EOF
echo "  - Added PIP_INDEX_URL and aliases to $SHELL_RC"


# 4. Rust & Go (Verification)
echo "[4/5] Verifying Rust/Go checksum environments..."
if command -v go &> /dev/null; then
    go env -w GOPROXY="https://proxy.golang.org,direct"
    echo "  - Go proxy set to default."
fi


# 5. Application of changes
echo "[5/5] Finalizing..."
echo "--- ✅ All configurations applied successfully ---"
echo "IMPORTANT: Please run 'source $SHELL_RC' to apply changes to this session."