#!/usr/bin/env bash

# ==============================================================================
# Development environment hardening (machine-local; ADR 0028)
# ------------------------------------------------------------------------------
# Writes the supply-chain guards that must NOT live in the committed repo:
#   - npm  ~/.npmrc               min-release-age=7 (7-day quarantine)
#   - uv   ~/.config/uv/uv.toml   flatt mirror (default index) + exclude-newer=7d
#   - go   GOPROXY                default checksum-verified proxy (if go present)
#   - win  persisted User PATH     append missing Git usr\bin + cmd (native Windows)
#
# Portable across GNU (Linux/WSL) and BSD (macOS): it uses NO `sed -i` at all,
# and is idempotent (safe to re-run — no duplicated lines).
#
# NOT written here: the pip index-url / pip-alias hardening block. That already
# lives in the tracked `.zshrc` and ships via `just deploy`; writing it here
# would dirty the symlinked repo file and duplicate on every re-run.
# ==============================================================================

set -eu

echo "--- 🛡️  Hardening environment (flatt mirror + 7-day quarantine) ---"

# 1. npm — idempotent min-release-age upsert (portable; no sed -i).
_npmrc="$HOME/.npmrc"
echo "[1/4] npm: ${_npmrc} (min-release-age=7)"
_tmp="$(mktemp)"
if [ -f "$_npmrc" ]; then
  # Drop any prior min-release-age line; `|| true` because grep -v exits 1
  # when every line is filtered out (e.g. a one-line file).
  grep -v '^min-release-age' "$_npmrc" >"$_tmp" || true
fi
printf 'min-release-age=7\n' >>"$_tmp"
mv "$_tmp" "$_npmrc"

# 2. uv — flatt default index + 7-day quarantine (overwrite = idempotent).
_uv_dir="$HOME/.config/uv"
echo "[2/4] uv: ${_uv_dir}/uv.toml (flatt default index + exclude-newer)"
mkdir -p "$_uv_dir"
cat >"${_uv_dir}/uv.toml" <<'EOF'
# Generated by scripts/harden_env.sh (machine-local; ADR 0028).
exclude-newer = "7 days"

[[index]]
name = "flatt"
url = "https://pypi.flatt.tech/simple/"
default = true
EOF

# Native Windows uv discovers user config at %APPDATA%\uv\uv.toml, not
# ~/.config/uv/uv.toml. Without the mirror the quarantine never applies
# there and any `uv run` rewrites committed uv.locks. APPDATA presence is
# the Windows signal (unset on Linux/macOS/WSL).
if [ -n "${APPDATA:-}" ]; then
  _uv_win_dir="$(cygpath -u "$APPDATA" 2>/dev/null || printf '%s' "$APPDATA")/uv"
  echo "  - windows: mirroring to ${_uv_win_dir}/uv.toml (native uv config path)"
  mkdir -p "$_uv_win_dir"
  cp "${_uv_dir}/uv.toml" "${_uv_win_dir}/uv.toml"
fi

# 3. go — default checksum-verified proxy (only if go is installed).
echo "[3/4] go: GOPROXY (default) if go is installed"
if command -v go >/dev/null 2>&1; then
  go env -w GOPROXY="https://proxy.golang.org,direct"
  echo "  - GOPROXY set to the default checksummed proxy"
else
  echo "  - go not on PATH; skipping"
fi

# 4. Windows persisted PATH — Git dirs (native Windows only; APPDATA is the
#    signal, like the uv mirror above). Fresh PowerShell sessions see only
#    the persisted (registry) PATH, and a stock setup can leave BOTH Git
#    dirs off it: usr\bin (cygpath — every just shebang recipe dies) and
#    cmd (git.exe itself — fresh sessions have no git at all; seen live).
#    Append whichever is missing to the User PATH (end position — shadows
#    nothing; no admin needed). Idempotent: the containment check skips
#    dirs already present. The in-process PATH is useless as a signal here
#    (Git Bash always self-prepends both), so read the registry.
# powershell.exe by absolute path when it is not on PATH — which is exactly
# the situation this section repairs (an incomplete persisted PATH can leave
# the current session without System32; seen live with an EMPTY Machine
# PATH). Only the 'User' scope is ever written — Machine PATH repair needs
# elevation and human review, so `just doctor` only detects and advises.
# HARDEN_ENV_SKIP_WIN_PATH=1 lets tests exercise the uv mirror with a fake
# APPDATA without touching the real registry.
_powershell() {
  if command -v powershell.exe >/dev/null 2>&1; then
    powershell.exe "$@"
  else
    "$(cygpath -u "${SYSTEMROOT:-C:\\Windows}")/System32/WindowsPowerShell/v1.0/powershell.exe" "$@"
  fi
}
if [ -n "${APPDATA:-}" ] && [ -z "${HARDEN_ENV_SKIP_WIN_PATH:-}" ] \
  && command -v cygpath >/dev/null 2>&1; then
  printf '%s\n' '[4/4] windows: persisted User PATH reaches Git usr\bin + cmd'
  _persisted="$(_powershell -NoProfile -Command \
    "[Environment]::GetEnvironmentVariable('Path','User') + ';' + [Environment]::GetEnvironmentVariable('Path','Machine')" \
    | tr -d '\r')"
  for _unix_dir in /usr/bin /cmd; do
    _win_dir="$(cygpath -w "$_unix_dir")"
    # containment check in pure bash: MSYS grep -i can abort (core dump)
    # on registry PATH strings with non-UTF8 (cp932) bytes
    if [[ "${_persisted,,}" == *"${_win_dir,,}"* ]]; then
      echo "  - ${_win_dir}: already on persisted PATH"
    else
      _powershell -NoProfile -Command \
        "[Environment]::SetEnvironmentVariable('Path', ([Environment]::GetEnvironmentVariable('Path','User').TrimEnd(';') + ';${_win_dir}'), 'User')"
      echo "  - ${_win_dir}: appended to persisted User PATH (open a new session to pick it up)"
    fi
  done
fi

echo "--- ✅ Hardening applied (machine-local; not tracked in the repo) ---"
